### ISSUE TITLE
Songs not deleted from SD card

### ISSUE THREAD

**Issue by maximbena** [h4h13/RetroMusicApp#10]
Hi
When I try to delete songs ('delete from this device') it says that songs have been deleted when in reality they are not deleted from my SD card.
Songs just disappears from the app, they are not deleted from the sdcard, and when I restart my phone they come back.
With other apps, songs are really deleted form the SD card.
Thanks

**Comment by h4h13** [comment]
External SD card support not added, if your editing/deleting /sharing songs from external SD card can't be done with using RetroMusicApp
